ALTER TABLE users ADD COLUMN phone VARCHAR(20) NULL;
ALTER TABLE addresses ADD COLUMN latitude DECIMAL(10,7) NULL, ADD COLUMN longitude DECIMAL(10,7) NULL;
ALTER TABLE orders
  ADD COLUMN subtotal BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN delivery_fee BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN distance_meters INT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN driver_delay_notice TINYINT(1) NOT NULL DEFAULT 0;
UPDATE orders SET subtotal=total WHERE subtotal=0 AND total>0;
ALTER TABLE payments
  MODIFY COLUMN status ENUM('UNPAID','PENDING','PAID','FAILED','EXPIRED','CANCELLED','REFUNDED') NOT NULL DEFAULT 'UNPAID',
  ADD COLUMN expires_at TIMESTAMP NULL;
CREATE TABLE print_jobs(
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  station ENUM('ADMIN','KITCHEN') NOT NULL,
  status ENUM('QUEUED','PRINTED','FAILED','REPRINTED') NOT NULL DEFAULT 'QUEUED',
  printer_key VARCHAR(50) NOT NULL,
  attempts INT UNSIGNED NOT NULL DEFAULT 0,
  reprint_count INT UNSIGNED NOT NULL DEFAULT 0,
  payload_json JSON NOT NULL,
  error_message VARCHAR(500) NULL,
  requested_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  printed_at TIMESTAMP NULL,
  UNIQUE KEY uq_print_job_order_station(order_id,station),
  INDEX idx_print_jobs_station_status(station,status,id),
  FOREIGN KEY(order_id) REFERENCES orders(id),
  FOREIGN KEY(requested_by) REFERENCES users(id)
);
