export const ROLES = Object.freeze({
  OWNER: "OWNER",
  MANAGER: "MANAGER",
  ADMIN: "ADMIN",
  KITCHEN: "KITCHEN",
  DRIVER: "DRIVER",
  CUSTOMER: "CUSTOMER",
});

export const FINAL_ROLES = Object.freeze(Object.values(ROLES));
const finalRoleSet = new Set(FINAL_ROLES);

export const CAPABILITIES = Object.freeze({
  OWNER_OVERSIGHT: "owner.oversight",
  REPORTS_READ: "reports.read",
  AUDIT_READ: "audit.read",
  STAFF_MANAGE: "staff.manage",
  CATALOG_READ: "catalog.read",
  CATALOG_WRITE: "catalog.write",
  STOCK_READ: "stock.read",
  STOCK_WRITE: "stock.write",
  PROMOTION_READ: "promotion.read",
  PROMOTION_WRITE: "promotion.write",
  SETTINGS_READ: "settings.read",
  SETTINGS_WRITE: "settings.write",
  LOYALTY_WRITE: "loyalty.write",
  DASHBOARD_READ: "dashboard.read",
  ORDERS_READ: "orders.read",
  ORDERS_OPERATE: "orders.operate",
  PAYMENTS_READ: "payments.read",
  PAYMENTS_VERIFY: "payments.verify",
  SUPPORT_CHAT: "support.chat",
  CUSTOMERS_MANAGE: "customers.manage",
  KITCHEN_PREPARE: "kitchen.prepare",
  DELIVERY_READ: "delivery.read",
  DELIVERY_OWN: "delivery.own",
  PRINTER_READ: "printer.read",
  PRINTER_OPERATE: "printer.operate",
  NOTIFICATIONS_READ: "notifications.read",
});

const permissions = new Map([
  [
    ROLES.OWNER,
    new Set([
      CAPABILITIES.OWNER_OVERSIGHT,
      CAPABILITIES.REPORTS_READ,
      CAPABILITIES.AUDIT_READ,
      CAPABILITIES.STAFF_MANAGE,
      CAPABILITIES.CATALOG_READ,
      CAPABILITIES.CATALOG_WRITE,
      CAPABILITIES.STOCK_READ,
      CAPABILITIES.STOCK_WRITE,
      CAPABILITIES.PROMOTION_READ,
      CAPABILITIES.PROMOTION_WRITE,
      CAPABILITIES.SETTINGS_READ,
      CAPABILITIES.SETTINGS_WRITE,
      CAPABILITIES.LOYALTY_WRITE,
      CAPABILITIES.DASHBOARD_READ,
      CAPABILITIES.ORDERS_READ,
      CAPABILITIES.ORDERS_OPERATE,
      CAPABILITIES.PAYMENTS_READ,
      CAPABILITIES.SUPPORT_CHAT,
      CAPABILITIES.CUSTOMERS_MANAGE,
      CAPABILITIES.DELIVERY_READ,
      CAPABILITIES.PRINTER_READ,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
  [
    ROLES.MANAGER,
    new Set([
      CAPABILITIES.CATALOG_READ,
      CAPABILITIES.CATALOG_WRITE,
      CAPABILITIES.STOCK_READ,
      CAPABILITIES.STOCK_WRITE,
      CAPABILITIES.PROMOTION_READ,
      CAPABILITIES.PROMOTION_WRITE,
      CAPABILITIES.SETTINGS_READ,
      CAPABILITIES.SETTINGS_WRITE,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
  [
    ROLES.ADMIN,
    new Set([
      CAPABILITIES.DASHBOARD_READ,
      CAPABILITIES.ORDERS_READ,
      CAPABILITIES.ORDERS_OPERATE,
      CAPABILITIES.PAYMENTS_READ,
      CAPABILITIES.PAYMENTS_VERIFY,
      CAPABILITIES.SUPPORT_CHAT,
      CAPABILITIES.CUSTOMERS_MANAGE,
      CAPABILITIES.KITCHEN_PREPARE,
      CAPABILITIES.DELIVERY_READ,
      CAPABILITIES.PRINTER_READ,
      CAPABILITIES.PRINTER_OPERATE,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
  [
    ROLES.KITCHEN,
    new Set([
      CAPABILITIES.ORDERS_READ,
      CAPABILITIES.KITCHEN_PREPARE,
      CAPABILITIES.PRINTER_READ,
      CAPABILITIES.PRINTER_OPERATE,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
  [
    ROLES.DRIVER,
    new Set([
      CAPABILITIES.ORDERS_READ,
      CAPABILITIES.DELIVERY_OWN,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
  [
    ROLES.CUSTOMER,
    new Set([
      CAPABILITIES.ORDERS_READ,
      CAPABILITIES.PAYMENTS_READ,
      CAPABILITIES.SUPPORT_CHAT,
      CAPABILITIES.NOTIFICATIONS_READ,
    ]),
  ],
]);

export function isFinalRole(role) {
  return finalRoleSet.has(role);
}

export function hasCapability(role, capability) {
  return permissions.get(role)?.has(capability) === true;
}

export function roleCapabilities(role) {
  return Object.freeze([...(permissions.get(role) || [])]);
}
